/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SongImport } from './routes/song'
import { Route as LiveImport } from './routes/live'
import { Route as BackgroundImport } from './routes/background'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SongRoute = SongImport.update({
  path: '/song',
  getParentRoute: () => rootRoute,
} as any)

const LiveRoute = LiveImport.update({
  path: '/live',
  getParentRoute: () => rootRoute,
} as any)

const BackgroundRoute = BackgroundImport.update({
  path: '/background',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/background': {
      id: '/background'
      path: '/background'
      fullPath: '/background'
      preLoaderRoute: typeof BackgroundImport
      parentRoute: typeof rootRoute
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveImport
      parentRoute: typeof rootRoute
    }
    '/song': {
      id: '/song'
      path: '/song'
      fullPath: '/song'
      preLoaderRoute: typeof SongImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  BackgroundRoute,
  LiveRoute,
  SongRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/background",
        "/live",
        "/song"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/background": {
      "filePath": "background.tsx"
    },
    "/live": {
      "filePath": "live.tsx"
    },
    "/song": {
      "filePath": "song.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
