/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as LiveIndexImport } from './routes/live/index'
import { Route as LiveTextImport } from './routes/live/text'
import { Route as LiveConfidenceImport } from './routes/live/confidence'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LiveIndexRoute = LiveIndexImport.update({
  path: '/live/',
  getParentRoute: () => rootRoute,
} as any)

const LiveTextRoute = LiveTextImport.update({
  path: '/live/text',
  getParentRoute: () => rootRoute,
} as any)

const LiveConfidenceRoute = LiveConfidenceImport.update({
  path: '/live/confidence',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/live/confidence': {
      id: '/live/confidence'
      path: '/live/confidence'
      fullPath: '/live/confidence'
      preLoaderRoute: typeof LiveConfidenceImport
      parentRoute: typeof rootRoute
    }
    '/live/text': {
      id: '/live/text'
      path: '/live/text'
      fullPath: '/live/text'
      preLoaderRoute: typeof LiveTextImport
      parentRoute: typeof rootRoute
    }
    '/live/': {
      id: '/live/'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  DashboardRoute,
  LiveConfidenceRoute,
  LiveTextRoute,
  LiveIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/live/confidence",
        "/live/text",
        "/live/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/live/confidence": {
      "filePath": "live/confidence.tsx"
    },
    "/live/text": {
      "filePath": "live/text.tsx"
    },
    "/live/": {
      "filePath": "live/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
