import { Song } from "./types";

export const schedule: Song[] = [
    {
      id: 'item1',
      title: 'Dengan Gambus dan Kecapi',
      lyrics: [
        "Dengan Gambus Dan Kecapi",
        "Mari Kita Puji Tuhan",
        "Bersoraklah, Bernyanyilah",
        "Bersuka Di Hadapan-Nya",
        "Serukanlah Nama Tuhan",
        "Yang Memberi Kemenangan",
        "Kalau Allah Di Pihak Kita",
        "Siapa Lawan Kita",
        "Terdengar Suara Tuhan Dari Sion",
        "Terdengar Suara Sorak Kegirangan",
        "Dari Umat Yang T'lah Dimenangkan",
        "Dari Umat Yang T'lah Dimenangkan",
      ],
      createdAt: new Date(Date.now()),
      updatedAt: new Date(Date.now()),
      scheduleId: 'Schedule1'
    },
    {
      id: 'item2',
      title: 'Berkat Anak Cucu',
      lyrics: [
        "Begitu gede, ",
        "kasih Allah pade kite",
        "Diberkatinlah anak cucu kite",
        "Di Mane Mane",
        "TUHAN nyang ngrobe ",
        "miskin di jadiin kaye",
        "Die nyang ngrendahin",
        "Die nyang ninggiin juge",
        "Berbahagialah",
        "Tiap orang nyang percaya",
        "anak cucu nye",
        "Kaga bakal jadi orang minte minte",
        "Keren TUHAN ",
        "genepin Firmanye",
        "Kaga ade nyang mustahil ",
        "Bagi orang percaye",
      ],
      createdAt: new Date(Date.now()),
      updatedAt: new Date(Date.now()),
      scheduleId: 'Schedule1'
    },
    {
      id: 'item3',
      title: 'Sukacita Penuaian',
      lyrics: [
        "Ketika Tuhan memulihkan keadaan sion",
        "Keadaan kita seperti orang yang bermimpi",
        "Waktu itu mulut kita penuh dengan tawa",
        "Lidah kita dengan sorak-sorai",
        "Yang menabur dengan mencucurkan air mata",
        "Akan menuai dengan bersorak-sorai",
        "Yang berjalan menangis sambil menabur benih",
        "Pasti pulang membawa berkas-berkasnya",
      ],
      createdAt: new Date(Date.now()),
      updatedAt: new Date(Date.now()),
      scheduleId: 'Schedule1'
    },
    {
      id: 'item4',
      title: 'Adalah Sukacita diHatiku',
      lyrics: [
        "Adalah sukacita di hatiku",
        "Di hatiku di hatiku",
        "Adalah sukacita di hatiku",
        "Dib'rikan Tuhanku",
        "Aku bahagia",
        "Bersukacita",
        "Ada kasih Yesus di hatiku",
        "Aku bahagia",
        "Bersukacita",
        "Ada kasih Yesus di hatiku",
        "Adalah damai sejahtera di dalam hatiku",
        "Di hatiku di hatiku",
        "Adalah damai sejahtera di dalam hatiku",
        "Dib'rikan Tuhanku",
      ],
      createdAt: new Date(Date.now()),
      updatedAt: new Date(Date.now()),
      scheduleId: 'Schedule1'
    },
    {
      id: 'item5',
      title: 'Mikir',
      lyrics: [
        "Kebaktian mulai jam sembilan",
        "Kamu selalu telat setengah jam",
        "Lalu kamu bilang yang terbaik sudah kau berikan",
        "Mikir!, Mikir!",
        "Pas giliran kasih persembahan",
        "Kamu selalu kasih yang recehan",
        "Lalu kamu bilang kamu suka korban buat Tuhan",
        "Mikir!, Mikir!",
        "Kok omongan gak sesuai kelakuan?",
        "Sama Tuhan, jangan suka kasih sembarangan",
        "Sama Tuhan, hidup harus dipertanggung jawabkan",
        "Sama Tuhan, jagalah kelakuan (A-iya-iya)",
        "Kalau nggak, namanya Kristen gadungan",
        "Pendeta lagi sharing firman",
        "Kamu malah sibuk WhatsApp-an",
        "Lalu kamu bilang kamu cinta banget kebenaran",
        "Mikir!, Mikir!",
        "Setiap bubaran kebaktian",
        "Kamu selalu ngacir duluan",
        "Lalu kamu bilang kamu cinta keluarga Tuhan",
        "Mikir!, Mikir!",
        "Kok omongan gak sesuai kelakuan?",
        "Sama Tuhan, jangan suka kasih sembarangan",
        "Sama Tuhan, hidup harus dipertanggung jawabkan",
        "Sama Tuhan, jagalah kelakuan (A-iya-iya)",
        "Kalau nggak, namanya Kristen gadungan",
        "La-la-la-la-la-la-la-la-la",
        "La-la-la-la-la-la-la-la-la",
        "O-lo-lo-la-la-le, tetet-toet-tetot, uwo-uwo",
        "La-la-la-la-la-la-la-la-la",
        "La-la-la-la-la-la-la-la-la",
        "O-lo-lo-la-la-le, tetet-toet-tetot, uwo-uwo",
        "Sama Tuhan, jangan suka kasih sembarangan",
        "Sama Tuhan, hidup harus dipertanggung jawabkan",
        "Sama Tuhan, jagalah kelakuan (A-iya-iya)",
        "Kalau nggak, namanya Kristen gadungan",
        "Sama Tuhan, jangan suka kasih sembarangan",
        "Sama Tuhan, hidup harus dipertanggung jawabkan",
        "Sama Tuhan, jagalah kelakuan (A-iya-iya)",
        "Kalau nggak, namanya Kristen tempelan",
        "Kalau nggak, namanya Kristen tiruan",
        "Kalau nggak, namanya Kristen gadungan",
      ],
      createdAt: new Date(Date.now()),
      updatedAt: new Date(Date.now()),
      scheduleId: 'Schedule1'
    },
    {
      id: 'item6',
      title: 'Terima Kasih yesus',
      lyrics: [
        "Terima Kasih Yesusku",
        "Puji Syukur Hanya bagi Tuhanku",
      ],
      createdAt: new Date(Date.now()),
      updatedAt: new Date(Date.now()),
      scheduleId: 'Schedule1'
    },
    {
      id: 'item7',
      title: 'Aku Masih Punya Tuhan',
      lyrics: [
        "Aku masih punya Tuhan, punya pengharapan",
        "Aku tetap beriman",
        "Tuhanku, Yesus kekuatanku, Yesus kekuatanku",
        "Aku masih punya Tuhan, hm-hm",
        "Aku masih punya Tuhan, punya pengharapan",
        "Aku tetap beriman",
        "Tuhanku, Yesus kekuatanku, Yesus kekuatanku",
        "Aku masih punya Tuhan",
        "Aku tetap percaya, tetap percaya",
        "Kau pembuat mukjizat di hidupku, oh-oh",
        "Aku tetap percaya, tetap percaya",
        "Takkan ku takut, Kau besertaku, uh-hu-uh-hu",
        "Aku masih punya Tuhan, punya pengharapan",
        "Aku tetap beriman",
        "Tuhanku, Yesus kekuatanku, Yesus kekuatanku",
        "Aku masih punya Tuhan",
        "Aku masih punya Tuhan (punya Tuhan), punya pengharapan",
        "Aku tetap beriman (aku beriman)",
        "Tuhanku, Yesus kekuatanku, Yesus kekuatanku",
        "Aku masih punya Tuhan, mm-hm",
        "Aku masih punya Tuhan",
      ],
      createdAt: new Date(Date.now()),
      updatedAt: new Date(Date.now()),
      scheduleId: 'Schedule1'
    },
  ]